environment: development
language: en-US # used in head <html class="no-js" lang="{{ site.language }}">
title: Bloocks fastest websites generator ever!
description: Build badass and fastest marketing websites with Bloocks, a static websites generator to build Ecommerce and websites on top of tecnical performaces.
name: <span class="ml-3 text-xl text-gray-800">Bl<span class="text-pink-500">o</span><span class="text-indigo-600">o</span>cks<span class="text-pink-500">!</span></span>


# for Jekyll SEO tag plugin and for using information into the project code structure
# Usage at https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

author :
  name : Antonio Trento
  email : lantoniotrento@gmail.com
  github : bloocks/bloocks.github.io
  twitter : bloocks
  facebook: bloocks
  linkedin: bloocks
  instagram: bloocks
  pinterest: bloocks

locale: en_US

logo: "/img/main-logo.png"

# google_site_verification: 1234

webmaster_verifications:
  # google: 1234
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234

social:
  name: Antonio Trento
  links:
    - https://twitter.com/lantoniotrento
    - https://www.facebook.com/lantoniotrento
    - https://www.linkedin.com/in/antoniotrento
    - https://github.com/antoniotrento
    - https://keybase.io/antoniotrento
    
twitter:
  username: bloocks
  card: large

facebook:
 # app_id: 12345 #the app id from https://developers.facebook.com/
 # admins: 12345 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 # publisher: 12345 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 # pixel: 12345


 # END CONFIG for Jekyll SEO tag plugin 

# Analytics

google :
    tracking_id : 'G-QSWTLSSE28' #Id google analitics
    amp_tracking_id: 'UA-184034920-1'
    # optimize_id : 'GTM-NF68992' #I'id di google optimize per A/B Testing
    # optimize_experiment_id: ' ' #I'id di dell'esperimento google optimize per A/B Testing
    tagmanager_id: 'GTM-TZFDWZR' #id di google tag manager
    amp_tagmanager_id: 'GTM-PD8KN8K'
    # ad_client: 'ca-pub-9204963049240271' # id google ADsense (to edit other id's of google ADsense go to /_includes/JB/ads-block-html )
    # ads_conversion_id: '' # id google ads_conversion_id
    # double_click_id: '' id google double_click

# Coockie consent by quantcast https://www.quantcast.com/products/choice-consent-management-platform/

quantcast:
  qcode: 'p-dvLkrYyUzKp8p'
  email: 'lantoniotrento@gmail.com'

# bloocks

# Menu

## Call to actions menu, link and text

cta:
  ctamenu: 'Yo! I&#39;m in!' # 'I&#39;m in!' for special characters use ASCII codes with &# after 'code_num' https://theasciicode.com.ar/ascii-printable-characters/braces-curly-brackets-opening-ascii-code-123.html
  ctamenulink: 'bloocker/'
  menuextra: 'Ask'
  menuextralink: 'ask/'

## Colors And typografy

### Primary colors

### Fonts color

### Globals

## Single Block Proprieties

# bloocks elements Sizes

# Text size

# Payment options
## Payment plugin

# Ecommerce
## Payment plugin


# This instruction that use http://jch.penibelst.de/ tech is used to delete all HTML comments

compress_html:
  comments: all

## jekyll-responsive-image https://github.com/wildlyinaccurate/jekyll-responsive-image need to have template file into _includes/ folder no upfolders or downfolders

#responsive_image:
#  template: _includes/srcset-resized-fallback.html
#  sizes:
#    - width: 1800
#    - width: 1200
#    - width: 800
#    - width: 480
#    - width: 320
#  base_path: img
#  output_path_format: img/resized/%{width}/%{basename}

## Jekyll picture tag https://rbuchberger.github.io/jekyll_picture_tag/
picture:
  source: "img"
  output: "img"
  suppress_warnings: true
  ignore_missing_images: true
  fast_build: true
  relative_url: false
  cdn_url: https://cdn.statically.io/img/bloocks.github.io/

# This command below can be uncomment when you have the image files uploaded 
# to your online repository to be able to serve your images from statically CDN
# (remember to upload the images only in the img folder and subfolders and on first commit the images to the server folder otherwise it will not work)

# cdn_url: https://cdn.statically.io/img/bloocks.github.io/img/ 

## Jekyll picture tag presets are in _data/picture.yml file from examples https://rbuchberger.github.io/jekyll_picture_tag/users/presets/examples.html

## don't works in leatest version of jekyll jekyll-imagemagick plugin for Jekyll picture tag https://rdoc.info/gems/jekyll-imagemagick

imagemagick:
  enabled: true
  widths:
    - 1024
    - 512
    - 0
  input_directories:
    - img
  input_formats:
    - ".png"
    - ".tiff"
  output_formats:
    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
    webp: "-quality 100%"

# From https://github.com/jekyllresources/jekyll-cloudinary
cloudinary:
  cloud_name: antoniotrento
  origin_url: https://res.cloudinary.com/antoniotrento/image/upload/
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      attributes:
        loading: "lazy"
    onethird:
      min_width: 110
      max_width: 535
      fallback_max_width: 300
      steps: 3
      sizes: "(min-width: 50rem) 17rem, 30vw"
      attributes:
        class: "one3rd"
        loading: "lazy"
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo
    figure:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    grayscale:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      effect: grayscale
      format: webp
      quality: 39
      attributes:
        loading: "lazy"

# Jekyll Admin create problems during the script npm run start, brosersync can't reload the site and give me an error and exit from the serving loop made in gulpfile.babel.js

# jekyll_admin:
#   hidden_links:
#     - posts
#     - pages
#     - staticfiles
#     - datafiles
#     - configuration

# This will require each of these plugins automatically.
plugins:
  - jekyll-cloudinary # https://github.com/nhoizey/jekyll-cloudinary
  - jekyll_picture_tag # https://rbuchberger.github.io/jekyll_picture_tag/
  - jekyll-target-blank # https://github.com/keithmifsud/jekyll-target-blank
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-menus # https://github.com/dojekyll/jekyll-menus
#  - jekyll-responsive-image # https://github.com/wildlyinaccurate/jekyll-responsive-image

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - postcss.config.json
  - postcss.config.js
  - build.js
  - docs
