# Meta

env:           "production"
docs_file:     "un.dojekyll.min"

# Build

markdown:      kramdown
permalink:     pretty
url:           http://localhost:4000
# baseurl:       https://dojekyll.github.io
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'bulma-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Configurations
logositename: JoJekyll

# This instruction that use http://jch.penibelst.de/ tech is used to delete all HTML comments

compress_html:
  comments: all

## Using autoprefixer for optimize CSS this task, is ipotetically done from the npm postcss tasks

# autoprefixer:
#  browsers:
#  - last 2 versions

## Gzip compression for github pages

# gzip:
#  replace_files: true
#  extensions:
#   - '.html'
#    - '.css'
#    - '.js'
  
## Social

# twitterapi: 'true'
# followbox: 'true'
facebook_url: https://facebook.com/lantoniotrento
twitter_url: https://twitter.com/lantoniotrento
linkedin_url: https://linkedin.com/in/antoniotrento
pinterest_url: https://www.pinterest.it/lantoniotrento/
instagram_url: https://instagram.com/lantoniotrento

## Jekyll picture tag https://rbuchberger.github.io/jekyll_picture_tag/
picture:
  source: "images"
  output: "images"
  suppress_warnings: true
  ignore_missing_images: true
  fast_build: true
  relative_url: false

## jekyll-imagemagick for Jekyll picture tag https://rdoc.info/gems/jekyll-imagemagick

imagemagick:
  enabled: true
  widths:
    - 1024
    - 512
    - 0
  input_directories:
    - images
  input_formats:
    - ".png"
    - ".tiff"
  output_formats:
    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
    webp: "-quality 100%"

# bloocks


## Colors And typografy

### Primary colors

### Fonts color

### Globals


## Single Block Proprieties


# bloocks elements Sizes


# Text size


# Payment options
## Payment plugin

# Ecommerce
## Payment plugin

# Analytics

# analytics: UA-82634666-2
# fbappid: 310296819307942

# From https://github.com/jekyllresources/jekyll-cloudinary
cloudinary:
  cloud_name: antoniotrento
  origin_url: https://res.cloudinary.com/antoniotrento/image/upload/
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      attributes:
        loading: "lazy"
    onethird:
      min_width: 110
      max_width: 535
      fallback_max_width: 300
      steps: 3
      sizes: "(min-width: 50rem) 17rem, 30vw"
      attributes:
        class: "one3rd"
        loading: "lazy"
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo
    figure:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    grayscale:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      effect: grayscale
      format: webp
      quality: 39
      attributes:
        loading: "lazy"        
      
input_types:
  - text
  - textarea
  - email
  - date
  - checkbox
  - radio
  - number
  - submit
  - recaptcha

form_engines:
  - cloudcannon
  - formspree
  - formbucket
  - netlify

# This will require each of these plugins automatically.
plugins:
  - jekyll-cloudinary
  - jekyll-gzip
  - jekyll-postcss
  - jekyll_picture_tag
  - jekyll-target-blank
#  - jekyll-zopfli
#  - jekyll-autoprefixer