environment: development
language: en-US # used in head <html class="no-js" lang="{{ site.language }}">
title: Bloocks fastest websites generator ever!
description: Build badass and fastest marketing websites with Bloocks, a static websites generator to build Ecommerce and websites on top of tecnical performaces.
name: <span class="ml-3 text-xl text-gray-800">Bl<span class="text-pink-500">o</span><span class="text-indigo-600">o</span>cks<span class="text-pink-500">!</span></span>


# for Jekyll SEO tag plugin and for using information into the project code structure

author :
  name : Antonio Trento
  email : lantoniotrento@gmail.com
  github : bloocks/bloocks.github.io
  twitter : bloocks
  facebook: bloocks
  linkedin: bloocks
  instagram: bloocks
  pinterest: bloocks

locale: en_US

logo: "/img/main-logo.png"

google_site_verification: 1234

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

social:
  name: Antonio Trento
  links:
    - https://twitter.com/lantoniotrento
    - https://www.facebook.com/lantoniotrento
    - https://www.linkedin.com/in/antoniotrento
    - https://github.com/antoniotrento
    - https://keybase.io/antoniotrento
    
twitter:
  username: bloocks
  card: large

facebook:
 app_id: 12345 #the app id from https://developers.facebook.com/
 admins: 12345 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 publisher: 12345 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 pixel: 12345


 # END CONFIG for Jekyll SEO tag plugin 


# bloocks


## Colors And typografy

### Primary colors

### Fonts color

### Globals


## Single Block Proprieties


# bloocks elements Sizes


# Text size


# Payment options
## Payment plugin

# Ecommerce
## Payment plugin

# Analytics

# analytics: UA-82634666-2
# fbappid: 310296819307942


# This instruction that use http://jch.penibelst.de/ tech is used to delete all HTML comments

compress_html:
  comments: all

## Jekyll picture tag https://rbuchberger.github.io/jekyll_picture_tag/
picture:
  source: "img"
  output: "img"
  suppress_warnings: true
  ignore_missing_images: true
  fast_build: true
  relative_url: false

## jekyll-imagemagick for Jekyll picture tag https://rdoc.info/gems/jekyll-imagemagick

imagemagick:
  enabled: true
  widths:
    - 1024
    - 512
    - 0
  input_directories:
    - img
  input_formats:
    - ".png"
    - ".tiff"
  output_formats:
    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
    webp: "-quality 100%"

# From https://github.com/jekyllresources/jekyll-cloudinary
cloudinary:
  cloud_name: antoniotrento
  origin_url: https://res.cloudinary.com/antoniotrento/image/upload/
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      attributes:
        loading: "lazy"
    onethird:
      min_width: 110
      max_width: 535
      fallback_max_width: 300
      steps: 3
      sizes: "(min-width: 50rem) 17rem, 30vw"
      attributes:
        class: "one3rd"
        loading: "lazy"
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo
    figure:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    grayscale:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
      effect: grayscale
      format: webp
      quality: 39
      attributes:
        loading: "lazy"

# Jekyll Admin create problems during the script npm run start, brosersync can't reload the site and give me an error and exit from the serving loop made in gulpfile.babel.js

# jekyll_admin:
#   hidden_links:
#     - posts
#     - pages
#     - staticfiles
#     - datafiles
#     - configuration

# This will require each of these plugins automatically.
plugins:
  - jekyll-cloudinary # https://github.com/nhoizey/jekyll-cloudinary
  - jekyll_picture_tag # https://rbuchberger.github.io/jekyll_picture_tag/
  - jekyll-target-blank # https://github.com/keithmifsud/jekyll-target-blank
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-menus # https://github.com/dojekyll/jekyll-menus

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - postcss.config.json
  - postcss.config.js
  - build.js
  - docs
